<?PHP
$seodate=date('d');

if ($seodate == '1') {
$thisKeys="STEM learning, STEM kits, Home Schooling Science Curriculum";
}
elseif ($seodate == '2') {
$thisKeys="New Science Curriculum, STEM Education, STEM Science, Pre-K Science Curriculum";
} 
elseif ($seodate == '3') {
$thisKeys="New Science Curriculum, STEM Education, STEM Science, Kindergarten Science Curriculum";
} 
elseif ($seodate == '4') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '5') {
$thisKeys="New Science Curriculum, STEM Education, STEM Science, Grade 1 Science Curriculum";
} 
elseif ($seodate == '6') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '7') {
$thisKeys="New Science Curriculum, STEM Education, STEM Science, Grade 2 Science Curriculum";
} 
elseif ($seodate == '8') {
$thisKeys="STEM learning, STEM kits, Home Schooling Science Curriculum";
} 
elseif ($seodate == '9') {
$thisKeys="New Science Curriculum, STEM Education, STEM Science, Grade 3 Science Curriculum";
} 
elseif ($seodate == '10') {
$thisKeys="STEM Kits, New Science Curriculum, Elementary school science";
} 
elseif ($seodate == '11') {
$thisKeys="New Science Curriculum, STEM Education, STEM Science, Grade 4 Science Curriculum";
} 
elseif ($seodate == '12') {
$thisKeys="STEM Science";
} 
elseif ($seodate == '13') {
$thisKeys="New Science Curriculum, STEM Education, STEM Science, Grade 5 Science Curriculum";
} 
elseif ($seodate == '14') {
$thisKeys="STEM Science";
} 
elseif ($seodate == '15') {
$thisKeys="New Science Curriculum, STEM Education, STEM Science, Grade 6 Science Curriculum";
} 
elseif ($seodate == '16') {
$thisKeys="STEM Science";
} 
elseif ($seodate == '17') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '18') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '19') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '20') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '21') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '22') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '23') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '24') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '25') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '26') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '27') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '28') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '29') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '30') {
$thisKeys="STEM Education Curriculum";
} 
elseif ($seodate == '31') {
$thisKeys="STEM Education Curriculum";
} 
else {
 $thisKeys="STEM Education Curriculum";
};

