<?PHP
$descdate=date('d');

if ($descdate == '1') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
}
elseif ($descdate == '2') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '3') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
elseif ($descdate == '4') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '5') {
$thisDesc="The first Core Science Curriculum developed by scientists, engineers, physicists, and educators. Coherent approach to teaching Science, Literacy, and Math based on the latest Neuroscience Research";
} 
elseif ($descdate == '6') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '7') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
elseif ($descdate == '8') {
$thisDesc="The first Core Science Curriculum developed by scientists, engineers, physicists, and educators. Coherent approach to teaching Science, Literacy, and Math based on the latest Neuroscience Research";
}
elseif ($descdate == '9') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '10') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
elseif ($descdate == '11') {
$thisDesc="The first Core Science Curriculum developed by scientists, engineers, physicists, and educators. Coherent approach to teaching Science, Literacy, and Math based on the latest Neuroscience Research";
} 
elseif ($descdate == '12') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '13') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
elseif ($descdate == '14') {
$thisDesc="The first Core Science Curriculum developed by scientists, engineers, physicists, and educators. Coherent approach to teaching Science, Literacy, and Math based on the latest Neuroscience Research";
} 
elseif ($descdate == '15') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '16') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
elseif ($descdate == '17') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '18') {
$thisDesc="The first Core Science Curriculum developed by scientists, engineers, physicists, and educators. Coherent approach to teaching Science, Literacy, and Math based on the latest Neuroscience Research";
} 
elseif ($descdate == '19') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
elseif ($descdate == '20') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '21') {
$thisDesc="The first Core Science Curriculum developed by scientists, engineers, physicists, and educators. Coherent approach to teaching Science, Literacy, and Math based on the latest Neuroscience Research";
} 
elseif ($descdate == '22') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
elseif ($descdate == '23') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '24') {
$thisDesc="The first Core Science Curriculum developed by scientists, engineers, physicists, and educators. Coherent approach to teaching Science, Literacy, and Math based on the latest Neuroscience Research";
} 
elseif ($descdate == '25') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
elseif ($descdate == '26') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '27') {
$thisDesc="The first Core Science Curriculum developed by scientists, engineers, physicists, and educators. Coherent approach to teaching Science, Literacy, and Math based on the latest Neuroscience Research";
} 
elseif ($descdate == '28') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
elseif ($descdate == '29') {
$thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
} 
elseif ($descdate == '30') {
$thisDesc="The first Core Science Curriculum developed by scientists, engineers, physicists, and educators. Coherent approach to teaching Science, Literacy, and Math based on the latest Neuroscience Research";
} 
elseif ($descdate == '31') {
$thisDesc="Knowing Science is working with School Districts to prepare for the transition to the NEXT GENERATION SCIENCE STANDARDS. STEM KNOWLEDGE integrated in every activity and grade level.";
} 
else {
 $thisDesc="Knowing Science, LLC was founded to help elementary school educators teach core concepts in science, beginning in the earliest grades. Using methods and materials that draw on the latest findings from cognitive neuroscience research, we design our products to develop children's knowledge of fundamental concepts such as measurement, distance, and force and motion.";
};

